### ISSUE TITLE
Replace all in code defined message for  internationalization 

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/AGSBS-infrastructure#51] opened 2018-02-12 16:08 UTC
For the internationalization all messages for warnings/errors etc. have to be replaced by gettext.
In the following listing all fix defined messages are listed with filenames(line number) followed by the message type :

- [ ] master.py (67) - NoLectureConfigurationError
- [ ] config.py (222) - ConfigurationError

**Comment by humenda** [comment] 2018-02-22 14:03
This is a duplicate of #42, please comment there.
Thanks

**Closed by humenda** 2018-02-22 14:03 UTC
